// Why: workflow snapshots expose DAG-owned children that never execute the parent's task tool.
export function getOmoWorkflowHelperLines(): string[] {
  return [
    '  let jobGraph',
    '  let workflowToolCallId',
    '  let workflowTerminal = false',
    '  function workflowStrings(value) {',
    "    return Array.isArray(value) && value.every((id) => typeof id === 'string')",
    '  }',
    '  function parseWorkflowGraph(value) {',
    '    if (!Array.isArray(value?.nodes) || !value.nodes.length) return undefined',
    '    const nodes = []',
    '    for (const node of value.nodes) {',
    "      if (typeof node?.id !== 'string' || !node.id) return undefined",
    '      const dependsOn = node.dependsOn === undefined ? [] : node.dependsOn',
    '      if (!workflowStrings(dependsOn)) return undefined',
    '      nodes.push({',
    '        nodeId: node.id, dependsOn: [...dependsOn],',
    "        ...(typeof node.label === 'string' ? { label: node.label } : {}),",
    "        ...(typeof node.taskId === 'string' && node.taskId ? { taskId: node.taskId } : {}),",
    "        ...(typeof node.state === 'string' ? { state: node.state } : {}),",
    '      })',
    '    }',
    '    const waves = Array.isArray(value.waves)',
    '      ? value.waves.map((wave) => Array.isArray(wave) ? wave : wave?.nodeIds) : undefined',
    '    return {',
    "      ...(typeof value.runId === 'string' ? { runId: value.runId } : {}),",
    "      ...(typeof value.name === 'string' ? { runLabel: value.name } : {}),",
    '      ...(waves?.every(workflowStrings) ? { waves: waves.map((wave) => [...wave]) } : {}),',
    '      nodes,',
    '    }',
    '  }',
    '  function captureWorkflowStart(event) {',
    '    const args = event.args ?? {}',
    "    if (args.action === 'start') {",
    '      jobGraph = parseWorkflowGraph(args.definition)',
    '      workflowTerminal = false',
    '      workflowToolCallId = event.toolCallId',
    "    } else if (args.action === 'attach' || (jobGraph?.runId && args.run_id === jobGraph.runId)) {",
    '      workflowToolCallId = event.toolCallId',
    '    }',
    '  }',
    '  function captureWorkflowEnd(event) {',
    '    const details = event.result?.details',
    '    const selected = event.toolCallId === workflowToolCallId',
    '    const snapshot = details?.snapshot ?? details?.result?.snapshot',
    '    if (!selected && (!jobGraph?.runId || details?.run_id !== jobGraph.runId)) return',
    "    if (event.isError || details?.kind === 'error') {",
    '      if (selected && !jobGraph?.runId) jobGraph = undefined',
    '      return',
    '    }',
    '    const graph = parseWorkflowGraph(snapshot)',
    '    if (graph) {',
    '      jobGraph = graph',
    "      workflowTerminal = ['completed', 'failed', 'cancelled'].includes(snapshot.status)",
    '      for (const node of graph.nodes) {',
    '        if (!node.taskId) continue',
    "        if (!taskRowIds.has(node.taskId)) upsertTask('workflow:' + node.taskId, node.taskId, node.label ?? node.nodeId)",
    "        const status = node.state === 'scheduled' ? 'pending' : node.state === 'skipped' ? 'cancelled' : node.state",
    '        applyStatus(node.taskId, status, undefined, false, true)',
    '      }',
    '      // Why: roster lifecycle normalization must not overwrite the authoritative DAG states.',
    '      jobGraph = graph',
    "    } else if (jobGraph && typeof details?.node_id === 'string' && typeof details?.task_id === 'string') {",
    '      jobGraph = { ...jobGraph, nodes: jobGraph.nodes.map((node) =>',
    '        node.nodeId === details.node_id ? { ...node, taskId: details.task_id } : node) }',
    '    }',
    '  }',
    '  // Why: RPC-only omo.dag.updated is not an extension hook; task observations keep joined nodes live.',
    '  function applyWorkflowTaskStatus(taskId, status, kind, runStats) {',
    '    if (!jobGraph || !taskId) return',
    "    const state = kind === 'revived' ? 'running' : status",
    "    if (state !== 'pending' && state !== 'running' && !TERMINAL_JOB_STATUS[state]) return",
    '    if (!jobGraph.nodes.some((node) => node.taskId === taskId)) return',
    "    if (kind === 'revived') workflowTerminal = false",
    '    jobGraph = { ...jobGraph, nodes: jobGraph.nodes.map((node) =>',
    '      node.taskId === taskId ? { ...node, state, ...(runStats ? { runStats } : {}) } : node) }',
    '  }',
    '  function retainRunningWorkflow() {',
    '    // Why: keep the final graph through settlement, like the roster, but not into an unrelated prompt.',
    "    if (workflowTerminal || jobGraph?.nodes.every((node) => TERMINAL_JOB_STATUS[node.state] || node.state === 'skipped')) {",
    '      jobGraph = undefined',
    '    }',
    '  }',
    "  pi.on('session_start', (event) => {",
    "    if (event.reason === 'reload') return",
    '    jobGraph = undefined',
    '    workflowToolCallId = undefined',
    '    workflowTerminal = false',
    '  })',
    ''
  ]
}
