import { getOmoWorkflowHelperLines } from './agent-status-omo-workflow-source'

// Why: the omo status extension derives a live background-job roster from `task` tool executions
// (omo exposes no separate child inventory). Kept in its own module so the shared handler-source
// file stays under the max-lines ratchet; only kind === 'omo' concatenates these lines.
export function getOmoJobRosterHelperLines(): string[] {
  // Why: session cwd is fixed for the omo process (transcripts live under it, not always under worktree); captured once at load.
  const sessionCwd = typeof process !== 'undefined' ? process.cwd() : undefined

  return [
    `  const sessionCwd = ${JSON.stringify(sessionCwd)};`,
    '  // Why: omo exposes task executions, not a separate background-job inventory.',
    '  const TERMINAL_JOB_STATUS = {',
    "    completed: 'succeeded', failed: 'failed', error: 'failed',",
    "    invalid_arguments: 'failed', plan_error: 'failed', denied: 'failed',",
    "    residency_denied: 'failed', owner_conflict: 'failed', start_failed: 'failed',",
    "    cancelled: 'cancelled', lost: 'cancelled', interrupted: 'cancelled',",
    '  }',
    '  const jobRoster = new Map()',
    '  const taskRowIds = new Map()',
    ...getOmoWorkflowHelperLines(),
    '  function rosterExtras() {',
    '    return {',
    '      ...(jobRoster.size ? { subagents: [...jobRoster.values()] } : {}),',
    '      ...(jobGraph ? { jobGraph } : {}),',
    '      ...(sessionCwd ? { sessionCwd } : {}),',
    '    }',
    '  }',
    '  // Why: retain running jobs preferentially; a background child outlives its spawn call.',
    '  function capRoster() {',
    '    while (jobRoster.size > 32) {',
    "      const evict = [...jobRoster.values()].find((e) => e.state !== 'working') ?? jobRoster.values().next().value",
    '      taskRowIds.delete(evict.job.taskId)',
    '      jobRoster.delete(evict.id)',
    '    }',
    '  }',
    '  function upsertTask(rowId, taskId, summary) {',
    "    const description = String(summary ?? '').slice(0, 200)",
    '    jobRoster.set(rowId, {',
    "      id: rowId, agentType: 'omo', description,",
    "      state: 'working', startedAt: Date.now(),",
    "      job: { taskId: taskId ?? rowId, lifecycle: 'running' },",
    '    })',
    '    if (taskId) taskRowIds.set(taskId, rowId)',
    '    capRoster()',
    '  }',
    "  // Why: omo-task.js merges run_stats (snake_case) into a terminal result's details; only",
    '  // finite numbers are real, so anything else is dropped rather than fabricated.',
    '  const RUN_STATS_FIELDS = [',
    "    ['turns', 'turns'], ['tool_calls', 'toolCalls'],",
    "    ['tokens_per_second', 'tokensPerSecond'], ['runtime_ms', 'runtimeMs'],",
    '  ]',
    '  function toRunStats(raw) {',
    "    if (typeof raw !== 'object' || raw === null) return undefined",
    '    const stats = {}',
    '    for (const [from, to] of RUN_STATS_FIELDS) {',
    '      if (Number.isFinite(raw[from])) stats[to] = raw[from]',
    '    }',
    '    return Object.keys(stats).length ? stats : undefined',
    '  }',
    '  // Why: a status carrying a known task_id resolves that row; a terminal status finishes it.',
    '  function applyStatus(taskId, status, fallbackRowId, isError, hasStatusResult, kind, runStats) {',
    '    applyWorkflowTaskStatus(taskId, status, kind, runStats)',
    '    const rowId = taskRowIds.get(taskId) ?? fallbackRowId',
    '    const entry = rowId != null ? jobRoster.get(rowId) : undefined',
    '    if (!entry) return',
    "    // Why: task_send can revive a finished resident child ({ kind: 'revived' }, no status); reopen it.",
    "    if (kind === 'revived') {",
    '      const tid = taskId ?? entry.job.taskId',
    '      taskRowIds.set(tid, entry.id)',
    "      jobRoster.set(entry.id, { ...entry, state: 'working', job: { ...entry.job, taskId: tid, lifecycle: 'running' } })",
    '      return',
    '    }',
    '    const terminal = TERMINAL_JOB_STATUS[status]',
    "    const known = status === 'pending' || status === 'running' || terminal !== undefined",
    '    // Why: a control result (task_send/task_output) carries a status-bearing details object with no',
    '    // recognizable status; leave the live row running, only adopting a newer task_id.',
    '    if (hasStatusResult && !known && !isError) {',
    '      if (taskId) { taskRowIds.delete(entry.job.taskId); taskRowIds.set(taskId, entry.id) }',
    '      if (taskId && taskId !== entry.job.taskId) {',
    '        jobRoster.set(entry.id, { ...entry, job: { ...entry.job, taskId } })',
    '      }',
    '      return',
    '    }',
    "    const lifecycle = terminal ?? (status === 'pending' || status === 'running' ? 'running' : (isError ? 'failed' : 'succeeded'))",
    '    if (taskId) {',
    '      taskRowIds.delete(entry.job.taskId)',
    '      taskRowIds.set(taskId, entry.id)',
    '    }',
    '    jobRoster.set(entry.id, {',
    "      ...entry, state: lifecycle === 'running' ? 'working' : 'idle',",
    '      job: { ...entry.job, taskId: taskId ?? entry.job.taskId, lifecycle, ...(runStats ? { runStats } : {}) },',
    '    })',
    '  }',
    '  // Why: a background child outlives the parent turn; a new prompt keeps only rows still',
    '  // running against a real task_id and drops finished or never-backgrounded tool rows.',
    '  function retainRunningJobs() {',
    '    retainRunningWorkflow()',
    '    for (const [rowId, entry] of [...jobRoster]) {',
    "      if (entry.state !== 'working' || entry.job.taskId === rowId) {",
    '        taskRowIds.delete(entry.job.taskId)',
    '        jobRoster.delete(rowId)',
    '      }',
    '    }',
    '  }',
    ''
  ]
}
